spring:
  datasource:
    url: jdbc:mysql://mysql:3306/jpop_karaoke
    username: root
    password: JpopSecretDB1@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

IMAGE_SERVER: http://nginx